Submission ran but did not finish its execution due to the errors below. 
This does not mean the program did not execute however, it may or may not have produced some files or none: 

 Traceback (most recent call last):
  File "***Removed due to privacy***/decrypt_z16075sc/./decrypt_z16075sc.py", line 67, in <module>
    ans+=MorseList[g]
KeyError: '.--.'

Output for test_file 2 was incorrect
Output files were found however no output file was found for test_file 3 with the correct name format
